- name: Get TIMEZONE from Host
  shell: timedatectl | grep "Time zone" | awk -F" " {'print $3'} | xargs
  register: timezone

- name: Create base ndt-server directory
  file:
    path: /home/monipeadm/ndt-server
    state: directory
    mode: '0755'
    owner: monipeadm

- name: Create certs directory
  file:
    path: /home/monipeadm/ndt-server/certs
    state: directory
    mode: '0755'
    owner: monipeadm

- name: Create datadir directory
  file:
    path: /home/monipeadm/ndt-server/datadir
    state: directory
    mode: '0755'
    owner: monipeadm

- name: Create var-spool-ndt directory
  file:
    path: /home/monipeadm/ndt-server/var-spool-ndt
    state: directory
    mode: '0755'
    owner: monipeadm

- name: Create var-local directory
  file:
    path: /home/monipeadm/ndt-server/var-local
    state: directory
    mode: '0755'
    owner: monipeadm

- name: Copy Site SSL Certificate
  copy:
    src: wildcard_medidor.rnp.br.cer
    dest: /home/monipeadm/ndt-server/certs/wildcard_medidor.rnp.br.cer
    mode: preserve

- name: Copy Site Private Key
  copy:
    src: wildcard_medidor.rnp.br.key
    dest: /home/monipeadm/ndt-server/certs/wildcard_medidor.rnp.br.key
    mode: preserve

- name: Container absent
  docker_container:
    name: ndt-server
    state: absent
  when: (ndt_info.force_pull is defined and ndt_info.force_pull == true)
  become: yes

- name: Image absent
  docker_image:
    name: danielneto/ndt-server:2.0
    source: pull
    state: absent
    force_absent: yes
  when: (ndt_info.force_pull is defined and ndt_info.force_pull == true)
  become: yes

- name: Docker NDT-Server Network
  docker_network:
    state: present
    name: macvlan-ndt
    driver: macvlan
    driver_options:
      parent: "{{ ndt_info.network.iface }}"
    ipam_config:
      - subnet: "{{ ndt_info.network.subnet }}"
        gateway: "{{ ndt_info.network.gateway }}"
  become: yes

- name: Docker RUN NDT-Server Cointainer
  docker_container:
    state: started
    name: ndt-server
    image: danielneto/ndt-server:2.0
    hostname: "{{ ndt_info.hostname }}"
    capabilities:
      - NET_BIND_SERVICE
    restart_policy: always
    tty: yes
    sysctls:
      net.ipv4.tcp_congestion_control: bbr
    networks:
      - name: macvlan-ndt
        ipv4_address: "{{ ndt_info.network.ipv4 }}"
    networks_cli_compatible: yes
    pull: true
    volumes:
      - /home/monipeadm/ndt-server/certs:/certs:ro
      - /home/monipeadm/ndt-server/datadir:/datadir:rw
      - /home/monipeadm/ndt-server/var-spool-ndt:/var/spool/ndt:rw
      - /home/monipeadm/ndt-server/var-local:/var/local:rw
    command: [
        "-cert", "/certs/wildcard_medidor.rnp.br.cer",
        "-key", "/certs/wildcard_medidor.rnp.br.key",
        "-datadir", "/datadir",
        "-ndt7_addr", ":4443",
        "-ndt7_addr_cleartext", ":8080"
      ]
    env:
      TZ: "{{ timezone.stdout }}"
      container: "docker"
  become: yes