#!/bin/sh

### BEGIN INIT INFO
# Provides:          gpsinit
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start GPS
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

RESULT=`ls -la /dev/gpspps0 | wc -l`
if [ "$RESULT" == "0" ]; then
        ln -sf /dev/ttyS0 /dev/gps0 ; ldattach pps /dev/ttyS0 ; ln -sf /dev/pps0 /dev/gpspps0
fi