#!/bin/sh

### BEGIN INIT INFO
# Provides:          gpsinit
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Start GPS
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

RESULT=`ls -la /dev/palisade0 | wc -l`
if [ "$RESULT" == "0" ]; then
        ntptime -N ; ln -s /dev/ttyS0 /dev/palisade0
fi