- name: perfSONAR | Check PPS startup
  copy:
    src: files/gpsinit
    dest: /etc/init.d/gpsinit
    mode: 0755

- name: perfSONAR | Configuring GPS link
  shell: /etc/init.d/gpsinit

- name: perfSONAR | Define PPS startup
  shell: chkconfig --add gpsinit